services:
  - type: web
    name: mindmap-builder
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
